export enum ErrorCodes {
  // Auth module
  AUTH_INVALID_CREDENTIALS = "AUTH_001",
  AUTH_TOKEN_EXPIRED = "AUTH_002",
  AUTH_INVALID_TOKEN = "AUTH_003",
  AUTH_ADMIN_ROLE_REQUIRED = "AUTH_004",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_005",
  AUTH_PASSWORD_TOO_WEAK = "AUTH_006",
  AUTH_USER_NOT_FOUND = "AUTH_007",
  AUTH_REFRESH_TOKEN_INVALID = "AUTH_008",
  AUTH_SELLER_ACCESS_REQUIRED = "AUTH_009",
  TENANT_SHOP_REQUIRED = "TENANT_001",
  TENANT_SHOP_ACCESS_DENIED = "TENANT_002",
  TENANT_SHOP_NOT_FOUND = "TENANT_003",
  TENANT_OWNER_REQUIRED = "TENANT_004",

  // Products module
  PROD_NOT_FOUND = "PROD_001",
  PROD_SLUG_EXISTS = "PROD_002",
  PROD_INVALID_CATEGORY = "PROD_003",
  PROD_INVALID_VOLUME_TIERS = "PROD_004",
  PROD_CANNOT_DELETE_WITH_ORDERS = "PROD_005",
  PROD_VARIANT_NOT_FOUND = "PROD_006",
  PROD_PLAN_NOT_FOUND = "PROD_007",
  PROD_VARIANT_HAS_STOCK = "PROD_008",

  // Orders module
  ORDER_NOT_FOUND = "ORDER_001",
  ORDER_INVALID_STATUS_TRANSITION = "ORDER_002",
  ORDER_CANNOT_DELIVER_INCOMPLETE = "ORDER_003",
  ORDER_STOCK_ITEMS_MISMATCH = "ORDER_004",
  ORDER_ALREADY_DELIVERED = "ORDER_005",
  ORDER_CANNOT_CANCEL = "ORDER_006",

  // Users module
  USER_NOT_FOUND = "USER_001",
  USER_EMAIL_EXISTS = "USER_002",
  USER_CANNOT_BAN_ADMIN = "USER_003",
  USER_INSUFFICIENT_BALANCE = "USER_004",
  USER_INVALID_TELEGRAM = "USER_005",
  USER_ROLE_CHANGE_DENIED = "USER_006",

  // Categories module
  CAT_NOT_FOUND = "CAT_001",
  CAT_SLUG_EXISTS = "CAT_002",
  CAT_PARENT_NOT_FOUND = "CAT_003",
  CAT_CIRCULAR_REFERENCE = "CAT_004",
  CAT_HAS_PRODUCTS = "CAT_005",

  // Coupons module
  COUPON_NOT_FOUND = "COUPON_001",
  COUPON_CODE_EXISTS = "COUPON_002",
  COUPON_INVALID_VARIANT = "COUPON_003",
  COUPON_EXPIRED = "COUPON_004",
  COUPON_MAX_REDEMPTIONS = "COUPON_005",
  COUPON_USER_LIMIT_EXCEEDED = "COUPON_006",

  // Stock module
  STOCK_NOT_FOUND = "STOCK_001",
  STOCK_ALREADY_RESERVED = "STOCK_002",
  STOCK_INVALID_STATUS = "STOCK_003",
  STOCK_INSUFFICIENT_QUANTITY = "STOCK_004",

  // Generic errors
  VALIDATION_ERROR = "VALID_001",
  UNAUTHORIZED = "AUTH_401",
  FORBIDDEN = "AUTH_403",
  NOT_FOUND = "GENERIC_404",
  INTERNAL_ERROR = "GENERIC_500",
}
