import { CanActivate, ExecutionContext, Injectable, UnauthorizedException } from '@nestjs/common';
import { getSharedPgPool } from '../../../../shared/infrastructure/pg-pool';
import { sha256Hex } from '../../../../shared/infrastructure/shop-secret-crypto';

export interface BotShopContext {
  shopId: string;
  botId: number;
}

interface BotShopRequest {
  headers: Record<string, string | undefined>;
  botShop?: BotShopContext;
}

const CACHE_TTL_MS = 30_000;
const cache = new Map<string, { value: BotShopContext; expiresAt: number }>();

/**
 * Resolves the shop from `x-bot-secret`: each shop's bot runner authenticates
 * with the internal secret generated by admin-backend, whose sha256 lives in
 * telegram_bots.secret_hash. Both bot and shop must be ACTIVE.
 */
@Injectable()
export class BotSecretGuard implements CanActivate {
  async canActivate(context: ExecutionContext): Promise<boolean> {
    const req = context.switchToHttp().getRequest<BotShopRequest>();
    const providedSecret = req.headers['x-bot-secret'];
    if (!providedSecret) {
      throw new UnauthorizedException('Missing bot secret.');
    }

    const botShop = await resolveBotShop(providedSecret);
    if (!botShop) {
      throw new UnauthorizedException('Invalid bot secret.');
    }

    req.botShop = botShop;
    return true;
  }
}

async function resolveBotShop(secret: string): Promise<BotShopContext | null> {
  const secretHash = sha256Hex(secret);
  const now = Date.now();
  const cached = cache.get(secretHash);
  if (cached && cached.expiresAt > now) return cached.value;

  const result = await getSharedPgPool().query<{ bot_id: number; shop_id: string }>(
    `SELECT tb.id AS bot_id, tb.shop_id::text AS shop_id
     FROM telegram_bots tb
     INNER JOIN shops s ON s.id = tb.shop_id
     WHERE tb.secret_hash = $1
       AND tb.status = 'ACTIVE'
       AND s.status = 'ACTIVE'
     LIMIT 1`,
    [secretHash],
  );
  const row = result.rows[0];
  if (!row) return null;

  const value: BotShopContext = { shopId: String(row.shop_id), botId: Number(row.bot_id) };
  cache.set(secretHash, { value, expiresAt: now + CACHE_TTL_MS });
  return value;
}
